nameOverride: ""
replicaCount: 1
podLabels: {}
podAnnotations: {}

configMap:
  # Specifies whether a configMap should be created (true by default)
  create: false

config: {}


image:
  repository: xiaoweiwang/otel-spring-webmvc
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
command:
  extraArgs: []

# Configuration for ports
ports:
  webmvc:
    enabled: true
    containerPort: 8080
    servicePort: 8080
    protocol: TCP

extraEnvs:
  - name: JVM_OPS
    value: -Dotel.traces.exporter=otlp -Dotel.service.name=otel-spring-mvc -Dotel.exporter.otlp.endpoint=http://localhost:4317
  - name: HOST_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
extraVolumes:
  - emptyDir: {}
    name: otel-agent
extraVolumeMounts:
  - mountPath: /app/otel
    name: otel-agent

# List of init container specs, e.g. for copying a binary to be executed as a lifecycle hook.
initContainers:
  - name: otel-agent
    image: xiaoweiwang/opentelemetry-javaagent:1.6.0
    volumeMounts:
      - name: otel-agent
        mountPath: /otel-agent

# Pod lifecycle policies.
lifecycleHooks: {}
# lifecycleHooks:
#   preStop:
#     exec:
#       command:
#       - /test/sleep
#       - "5"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080

resources:
  limits:
    cpu: 1
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
# Allows for pod scheduler prioritisation
priorityClassName: ""


